"""se agrega al backend la posibilidad de subir imagenes, tanto de productos como de perfil

Revision ID: 5f8358c8f525
Revises: ebf668ea8857
Create Date: 2025-04-06 23:11:39.848866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8358c8f525'
down_revision: Union[str, None] = 'ebf668ea8857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
