"""cambio en upload.py para solucionar el tema de las imagenes, se agregan get y otro post

Revision ID: 64c553213d50
Revises: d5af56cfc498
Create Date: 2025-04-08 20:41:03.807584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c553213d50'
down_revision: Union[str, None] = 'd5af56cfc498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
