"""Acomodando endpoints de cupones, ordenes y products

Revision ID: 82a0082e26d8
Revises: e3fb3a1100de
Create Date: 2025-04-05 11:49:13.253491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a0082e26d8'
down_revision: Union[str, None] = 'e3fb3a1100de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
