"""Agrega herencia de productos: SportsProduct y FoodProduct

Revision ID: f40ec405e150
Revises: 7c2a05b1cb04
Create Date: 2025-03-31 12:38:05.135933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40ec405e150'
down_revision: Union[str, None] = '7c2a05b1cb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type')
    # ### end Alembic commands ###
